# These values are the only ones required to use the application
# locally as a regular clients. Even if not provided these are
# the default values.
client:
  node: algo-did.aidtech.network:443
  timeout: 5
  pow: 16
# These values are required to run an agent node.
agent:
  pow: 8
  port: 9090
  http: true
  proxy_protocol: true
  env: dev
  storage:
    kind: ephemeral
  method:
    - algo
  tls:
    enabled: false
    cert: /etc/algoid/tls/tls.crt
    key: /etc/algoid/tls/tls.key
    system_ca: true
    custom_ca: []
  network:
    algod:
      address: "..."
      token: "..."
    indexer:
      address: "..."
      token: "..."
