apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "algo-id.fullname" . }}
  labels:
    {{- include "algo-id.labels" . | nindent 4 }}
data:
  config.yaml: |-
  {{- toYaml .Values.configuration | nindent 4 }}
