{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "algo-id.serviceAccountName" . }}
  labels:
{{ include "algo-id.labels" . | nindent 4 }}
{{- end -}}
