apiVersion: v1
kind: Service
metadata:
  name: {{ include "algo-id.fullname" . }}
  labels:
    {{- include "algo-id.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
  selector:
    {{- include "algo-id.selectorLabels" . | nindent 4 }}
