{{- $fullName := include "postgres.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-credentials" $fullName }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.config.user }}
  password: {{ .Values.config.password | default (randAlphaNum 32) | b64enc | quote }}
