{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "algo-node.storage" . }}
  labels:
    {{- include "algo-node.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
---
{{- end -}}
