{{- $fullName := include "algo-node.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" $fullName }}
  labels:
    {{- include "algo-node.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.config.token | default (randAlphaNum 64) | b64enc | quote }}
